sql:
  name: ${env:SQL_NAME,postgres}
  password: ${env:SQL_PASSWORD,habitat1}
  dbname: ${env:SQL_DBNAME,postgres}
  host: ${env:SQL_HOST,localhost}
  graph: ${env:SQL_GRAPH,graph_model}
  provenance: ${env:SQL_PROVENANCE,nb_provenance}
  dbs: ${env:SQL_DBS,rowstore}
  cellcode: ${env:SQL_CELLCODE, nb_cellcode}
  nb_info: ${env:SQL_INFO, nb_info}
  nottablevar: ${env:SQL_NOTTABLEVAR, not_table_var}
  knn_sim_list: ${env:KNN_LIST, knn_sim_list}
neo:
  name: ${env:NEO_NAME,neo4j}
  password: ${env:NEO_PASSWORD,habitat1}
  host: ${env:NEO_HOST,localhost:7474}
  db: ${env:NEO_DB,data}