# Generated by Django 3.2.2 on 2021-05-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_node_id', models.PositiveBigIntegerField()),
                ('successor_node_id', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.PositiveIntegerField()),
                ('node_type', models.CharField(max_length=200)),
                ('node_contents', models.TextField()),
            ],
        ),
    ]
