# Generated by Django 3.2.2 on 2021-05-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edge',
            new_name='QueryEdge',
        ),
        migrations.RenameModel(
            old_name='Node',
            new_name='QueryNode',
        ),
    ]
