# Generated by Django 3.2.2 on 2021-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20210518_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=200)),
            ],
        ),
    ]
