# Generated by Django 3.2.2 on 2021-06-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_querylibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=200)),
                ('query_contents', models.TextField()),
            ],
        ),
    ]
